AWSTemplateFormatVersion: "2010-09-09"
Description: Enable CloudTrail with S3 Bucket and Bucket Policy

Parameters:

  TrailName:
    Type: String
    Default: "CfnAPITracer"
    Description: For tracing API calls

Resources:

  CloudTrailBucket:
    Type: AWS::S3::Bucket
    Properties: {}

  CloudTrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudTrailBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: s3:GetBucketAcl
          Condition:
            StringEquals:
              aws:SourceArn: !Sub "arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/${TrailName}"
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
          Resource: !Sub "arn:aws:s3:::${CloudTrailBucket}"
          Sid: AWSCloudTrailAclCheck20150319
        - Action: s3:PutObject
          Condition:
            StringEquals:
              aws:SourceArn: !Sub "arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/${TrailName}"
              s3:x-amz-acl: bucket-owner-full-control
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
          Resource: !Sub "arn:aws:s3:::${CloudTrailBucket}/*"
          Sid: AWSCloudTrailWrite20150319

  CloudTrail:
    DependsOn:
      - CloudTrailBucketPolicy
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: !Ref TrailName
      S3BucketName: !Ref CloudTrailBucket
      IncludeGlobalServiceEvents: false
      IsMultiRegionTrail: false
      EnableLogFileValidation: false
      IsLogging: true

Outputs:

  TrailARN:
    Value: !GetAtt CloudTrail.Arn

  BucketName:
    Value: !Ref CloudTrailBucket
